### ISSUE TITLE
Support Icon Is Unclear

### ISSUE THREAD

**Issue by Jake-Rich** [theumod/umod.org#51] opened 2018-04-17 19:43 UTC
It's super unclear that the orange button is a life raft, and the life raft means support.

Just have some kind of text above the buttons:

      Help                Source Code
(Orange Button)  (Github Button)

**Comment by lukespragg** [comment] 2018-04-17 19:44
Duplicate of https://github.com/theumod/umod.org/issues/50 that I just opened before this. ;)

**Closed by lukespragg** 2018-04-17 19:44 UTC
